extends: default
rules:
  document-start: disable
  line-length: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy:
    level: warning
    allowed-values: ['true', 'false', 'on']
