name: lint xml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/xcop-action@master
        with:
          files: |
            **/*.xml
            **/*.fxml
