name: lint-yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint-yml:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/workflows/yamllint.yaml
