name: lint java
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-java:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check
