name: lint yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-yml:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/.yamllint.yml
