name: lint markdown
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-markdown:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
