name: lint action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-action:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
      - run: |
          ./actionlint -color
