name: lint java
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven
      - run: ./mvnw checkstyle:check
