name: Java CI

on: [ push, pull_request ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Dependency Analyze
        run: ./mvnw dependency:analyze

      - name: Checkstyle
        run: ./mvnw checkstyle:check

  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Verify build
        run: ./mvnw verify

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Verify build
        run: ./mvnw.cmd verify
