name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            maven_command: "./mvnw"

          - os: windows-latest
            maven_command: "./mvnw.cmd"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Verify build
        run: ${{ matrix.maven_command }} clean verify

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Dependency Analyze
        run: ./mvnw dependency:analyze

      - name: Checkstyle
        run: ./mvnw checkstyle:check
