name: verify-maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify-maven:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            maven_command: "./mvnw"
          - os: windows-latest
            maven_command: "./mvnw.cmd"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
          cache: maven
      - run: ${{ matrix.maven_command }} clean verify
